version: '2'
services:
  mariadb:
    image: 'mariadb:10.1'
    environment:
      - MARIADB_USER=RISHABH
      - MARIADB_DATABASE=DBOS
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/rishabh'
  joomla:
    image: 'joomla:3'
    environment:
      - MARIADB_HOST:mariadb
      - MARIADB_PORT_NUMBER:1234
      - JOOMLA_DATABASE_USER=RISHABH
      - JOOMLA_DATABASE_NAME=DBOS
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'joomla_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  joomla_data:
    driver: local
